
stages:
- test

unit_trainer:
  stage: test 
  image: tensorflow/tensorflow:2.9.1
  script:
    - pip install pytest
    - pip install -e . 
    - pytest tests --junitxml=report.xml
  artifacts:
    when: always
    reports:
      junit: report.xml

  #if: $CI_PIPELINE_SOURCE == 'merge_request_event'

coverage test:
  stage: test
  image: tensorflow/tensorflow:2.9.1
  script:
    - pip install pytest pytest-cov
    - pip install -e .
    - coverage run -m pytest tests
    - coverage report -i
    - coverage xml -i
  coverage: '/(?i)total.*? (100(?:\.0+)?\%|[1-9]?\d(?:\.\d+)?\%)$/'
  artifacts:
    reports:
      coverage_report:
        coverage_format: cobertura
        path: coverage.xml
        