autolog: False
optimizer: 
  - SGD
  - PiecewiseConstantDecay: 
      boundaries: [200, 300, 400]
      values:  [0.003, 0.0003,0.00003,0.000003]
batch_size: 64 
loss: 
  SparseCategoricalCrossentropy: 
      from_logits: True
callbacks:
    - EarlyStopping:
        monitor: val_accuracy
        patience: 2
        restore_best_weights: True  
verbose: 1 
epochs: 1
shuffle: False
class_weights: 
    - False
accelerator: cpu 
steps_per_epoch: 1
