autolog: False
optimizer: 
  - Adam
  - PiecewiseConstantDecay: 
      boundaries: [200, 300, 400]
      values:  [0.003, 0.0003,0.00003,0.000003]
batch_size: 64 
loss: 
  SparseCategoricalCrossentropy: 
      from_logits: True
callbacks:
    - EarlyStopping:
        monitor: val_accuracy
        patience: 2
        restore_best_weights: True  
verbose: 1 # 0, 1, 2 
epochs: 1
# shuffle: False
class_weights: # First value is boolean
    - False
accelerator: cpu #Make it optional
steps_per_epoch: 1